services:
  - name: FastfilService
    type: web
    env: java
    region: oregon
    buildCommand: |
      chmod +x gradlew
      ./gradlew build
    startCommand: java -jar build/libs/kemi-0.0.1-SNAPSHOT.jar
    plan: free
    healthCheckPath: "/actuator/health"
    autoDeploy: true